learning_user/Contact_Info_Adminstration/urls.py
from . import views
from django.urls import path


app_name = 'Contact_Info_Adminstration'

urlpatterns = [
    path('', views.PostList.as_view(), name='home'),
    path('<slug:slug>', views.PostDetail.as_view(), name='post_detail'),
    path('contact/', views.contact_form, name='contact'),
   
  
]

learning_user/accounts/urls.py
from django.urls import path
from . import views
from .views import (evalList, EvalCreateView, EvalUpdateView, EvalDeleteView,
    cherList, CherCreateView, CherDeleteView, CherUpdateView, HomePageView

,confList,ConfUpdateView,ConfCreateView,
ConfDeleteView,ConfDetailView,ArticlList_Conf, Confmodifier

,ComiteCreateView, ComiteUpdateView
    )



urlpatterns = [
    
    # les liste li3ndnaaaaaaaaaaaaaaaaaaaa ga3 f jiha t3na admin 
    path('',HomePageView.as_view(),name ="dashboard"),
    path('gest_eval/', evalList.as_view(), name="ges_eval"),
    path('gest_cher', cherList.as_view(), name="ges_cher"),
     path('gest_conf/', confList.as_view(), name="ges_conf"),




#++++++++++++++++++++++ admin men jihete chandiire lel  eval
    path('evalEdit/<str:pk>/', EvalUpdateView.as_view(), name="editEval"),
    path('evalCreate/', EvalCreateView.as_view(), name="createEval"),
    path('<pk>/deleteEval/', EvalDeleteView.as_view(), name="deleteEval"), 
  

#++++++++++++++++++++++++++ admin men jihete chandiire lel  chrchr
    
    path('editCher/<str:pk>/', CherUpdateView.as_view(), name="editCher"),
    path('createCher/', CherCreateView.as_view(), name="createCher"),
    path('<pk>/deleteCher/', CherDeleteView.as_view(), name="deleteCher"),
   

         

    # hadi kante aapliaction smoha Gconf ms ni hatiteh f account bch ndiro 
    #app wahde lel adminnstration  w kate dyera des prblm  ni riglthoom rahi f chbebe
    
    #++++++++++++++++++++++++++ admin men jihete chandiire lel  cConfrencess

   
    path('confEdit/<str:pk>/', ConfUpdateView.as_view(), name="confEdit"),
    path('confCreate/', ConfCreateView.as_view(), name="confCreate"),
    path('<pk>/deleteConf/', ConfDeleteView.as_view(), name="deleteConf"), 
    path('confDetail/<str:pk>/', ConfDetailView.as_view(), name="confDetail"),
    path('modifier/<str:pk>/', Confmodifier.as_view(), name="modifier"),
    
    
    
# +++++++ 2020/05/15 +++++++++
    path('article_conf/<str:pk>/',ArticlList_Conf,name='article_conf'),
    path('comiteCreate',ComiteCreateView.as_view(),name='comiteCreate'),
    path('comiteEdit/<str:pk>/', ComiteUpdateView.as_view(), name="comiteEdit"),
    
  



    
]


    

learning_user/learning_user/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views as viewsPj
from mybasic_app.views import chercheur, evaluteur,views
from django.conf import settings



#####################
from Contact_Info_Adminstration.views import search_view




urlpatterns = [
    path('1salah2toufik3ahmed4islam5nadjet6nariman789/', admin.site.urls), #hadaa path tree essencieles attention
    path('',viewsPj.Homme,name='homme'),
    path('AbouteUs',viewsPj.Aboute__Us,name='Aboute__Us'),



    path('myapp/',include('mybasic_app.urls')),
    path('logout/',views.user_logout,name="logout"),
     path('contact/', include('Contact_Info_Adminstration.urls')),



######
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/chercheur/', chercheur.ChercheurSignUpView.as_view() , name='chercheur_signup'),
    path('accounts/signup/evaluteur/', evaluteur.EvaluteurSignUpView.as_view(), name='evaluteur_signup'),

################## note perssonel
    path('<int:id>',views.mylist, name="mylist"),


#++++++++++++++++++++++++++++++++++++++++++++++++++++#partie adminstration 
path('MakaniAdmin/', include('accounts.urls'),name='MakaniAdmin'),

#############  2020/05/15   ########"
    path('Info-Poste', viewsPj.Poste_page,name='Info_Poste'),
    path('blog/', include('Poste_By_Admin.urls')),
    path('search/', search_view,name='searching'),




############      2020 / 05 / 18 ################""""

    path('G__evaluation/', include('G__evaluation.urls')),






]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_user/mybasic_app/urls.py
from django.urls import path,include
from .views import chercheur,evaluteur,views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    
     path('login/',views.LoginByProfile, name="LoginByProfile"),

    


###################""


  path('myapp/chercheur/', include(([
  	  path('', chercheur.profil_chrch, name='dashboardchrch'),
      path('contact',chercheur.ToContact , name='Contact_chrch_ou_admin'),
      path('myprofile_AsChercheur',chercheur.Userchrch,name='Profile'),
      path('CréaArticle',chercheur.CreeArticle,name='CreeArticle'),
      path('DeleteARTCL',chercheur.Delete_list,name='list_delete_Article'),
      path('UpdateARTCL',chercheur.Update_detaille_list,name='tach_ARTCL'),
      path('Documentation_chrh/',chercheur.AccedeauDoc_Aschrch,name='AccedeauDoc_Aschrch'),
      path('EditeProfile/<str:pk>/',chercheur.Edit_Myprofil.as_view(),name='EditeProfile'),
              # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++   10/05/2020     ++++++++++++++++++++++++++++++++++
  
      path('DeleteARTCL/<str:pk>/',chercheur.Delete,name='Delate'),
      path('UpdateArTCL/<str:pk>/',chercheur.Update,name='Update'),
              # +++++++++++++++++++++++++++++++++++++++++++++   15/05/2020     ++++++++++++++++++++++++++++++++++
      path('conf_list/<str:pk>/',chercheur.confList,name='conf_list'),
      path('conf_detaille/<str:pk>/',chercheur.ConfDetailView.as_view(),name='conf_detaille'),
      path('topic_list/',chercheur.topicList.as_view(),name='topic_list'),



    

                                     ], 'views'), namespace='chercheur')),





    path('myapp/evaluteur/', include(([

       path('', evaluteur.profil_eval , name='dashboardeval'), # hadi engenrale
       path('contact',evaluteur.ToContact , name='Contact_eval_ou_admin'),
       path('myprofileAsEvaluateur/',evaluteur.Usereval,name='Profile'),  # hadi sepecile lel user
       path('Articles/',evaluteur.Liste_All_Artcl.as_view(), name='listeArtcile'),
       path('Confrences/',evaluteur.Liste_All_Confrence.as_view() , name='All_Confernce'),
       path('Liste/',evaluteur.all_list , name='listeNv'),# z3ma ga3 les them wla confrence
       path('Evalution/',evaluteur.evaluéé , name='evaluéé'),
       path('Documentation_evl',evaluteur.AccedeauDoc,name='AccedeauDoc'),
       path('EditeProfile/<str:pk>/',evaluteur.Edit_Myprofil_As_Eval.as_view(),name='EditeProfileAs_eval'),
       path('etat_chrch/',evaluteur.All_Etat_Du_Cherchr.as_view() , name='Etat_All_Chrch'),


       path('Allcommite/',evaluteur.All_Commite.as_view() , name='AllCommite'),
       #path('Votrecommite/',evaluteur.Mon_Commite.as_view() , name='MonCommite'),





                                      ], 'views'), namespace='evaluteur')),





###############" hado swalhe persssonel t3 kol user bch ytfkre wla ki agendaa "

    path('create/',views.createNote, name="create"),
    path('mynote/',views.mynote, name="mynote"),
    path('merci/',views.Merci, name="merci"),


  


    
        ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_user/Contact_Info_Adminstration/models.py
from django.db import models
from learning_user import settings

# create a tuple for the status of each post
STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


# each field in this class represents a column in the database table
class Contact_MAKANI_CF(models.Model):
    title_de_problem = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    Perssone = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now=True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    # this class contains metadata and uses the created_on field from the model to sort out data which sorts
    # in descending order by default
    class Meta:
        ordering = ['-created_on']

    # this method is the default human-readable representation of the object. Django will use it in many places
    # such as the admin panel
    def __str__(self):
        return self.title_de_problem




################  2020-05-15 ######

class SearchQuery(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.SET_NULL)
    query = models.CharField(max_length=220)
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.query

    class Meta:  
        verbose_name = "Plus_Commande_pour_les_users"



        

learning_user/Contact_Info_Adminstration/forms.py
from django import forms
from django.contrib.auth.models import User



def should_be_empty(value):
    if value:
        raise forms.ValidationError('Field is not empty')


class ContactForm(forms.Form):
    Sujet = forms.CharField(max_length=80)
    Message_Detailles = forms.CharField(widget=forms.Textarea)
    email = forms.EmailField()
    forcefield = forms.CharField(
        required=False, widget=forms.HiddenInput, label="Leave empty", validators=[should_be_empty])

learning_user/mybasic_app/forms.py
from django import forms
from mybasic_app.models import ToDolist
from django.core import validators



from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from mybasic_app.models import (Chercheur, User ,Evaluateur,Article , Conferance , Article)
from django.forms.utils import ValidationError



'''
def check_for_z(value):
    if value[0].lower() != '' :
        raise forms.ValidationError("NAME MUST BE STARTS BY  Z ")

'''



class EvaluteurSignUpForm(UserCreationForm):
    
    email = forms.EmailField(error_messages={'exists': 'This already exists!'})
    verify_email=forms.EmailField()
    Code_Eval = forms.CharField(max_length=30)
    

    ## kyn li rani mkhlihom w kyn li suppp
    ## li khlithom li9 ykono bch verifee wla rahom sepicei
    ### li mhithom pcq deja kynin model  donc 
    ## be   class >> UserCreationForm  y3rfhom

    class Meta(UserCreationForm.Meta):
  
        model = User
        fields=('first_name','last_name','username','password1','password2',
            'email','verify_email','Code_Eval','Organization','Country','site_Personnel',
            'City','Post_code','Address_line_principale','Address_line','Phone',
            'profile_pict',)

     

    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if User.objects.filter(email=email).exists():
            raise ValidationError(" No !!!  ,  Email exists")


        if vmail != email :
            raise forms.ValidationError(" CHECK Your :  EMIAL !!! ")
        


    def save(self, commit=True):
        user = super().save(commit=False)
        user.profile_pict = self.cleaned_data.get('profile_pict')
        user.is_evaluteur = True
        if commit:
            user.save()
            evaluteur=Evaluateur.objects.create(user=user)
            evaluteur.email=self.cleaned_data.get('email')
            evaluteur.Code_Eval=self.cleaned_data.get('Code_Eval')

            evaluteur.save()
        return user








###############













class ChercheurSignUpForm(UserCreationForm):
 
    email = forms.EmailField()
    verify_email=forms.EmailField(required=True)   
    Info_personel =forms.CharField(required=False)


    class Meta(UserCreationForm.Meta):
        model = User
        fields=('first_name','last_name','username','password1','password2',
            'email','verify_email','site_Personnel','Organization','Country','Phone',
            'City','Post_code','Address_line_principale','Address_line',
            'profile_pict','Info_personel')

     
    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']

        if User.objects.filter(email=email).exists():
            raise ValidationError(" No !!!  ,  Email exists")

        if vmail != email :
            raise forms.ValidationError(" CHECK Your :  EMIAL ! ")
        


    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.profile_pict = self.cleaned_data.get('profile_pict')
        user.is_chercheur = True          #juste pour save extnde kima ngilo f User"
        user.save()
        chercheur = Chercheur.objects.create(user=user)
        chercheur.email=self.cleaned_data.get('email')     #Juste bch save the personel 3ndek "


        chercheur.save()
        
        return user





class createNotelist(forms.ModelForm):
    
    class Meta():
        model = ToDolist
        fields = ('name',)


# +++++++++++++++++++++++++++++++  10/05/2020 ++++++++++++++++++++++++++++++++++++++++ 


class From_Edite_Profile(forms.ModelForm):
    
    Info_personel =forms.CharField(required=False)

    class Meta():
        model=User
        fields=('first_name','last_name','username','email',
        'site_Personnel','Organization','Country','Phone',
        'City','Post_code','Address_line_principale','Address_line',
            'profile_pict','Info_personel')





class ArticleForm(forms.ModelForm):

    name = forms.CharField(label='Article name ..',
                           widget=forms.TextInput(attrs={'placeholder': ' Article name'}))

    class Meta:
        model = Article
        fields = ['name' , 'description', 'Conferance','document']
        widgets = {

            'name': forms.TextInput(attrs={'class': 'form-control'}),

            'description': forms.TextInput(attrs={'class': 'form-control'}),
        }




class ConfForm(forms.ModelForm):
    class Meta:
        model = Conferance
        fields = '__all__'

learning_user/Contact_Info_Adminstration/views.py
from django.shortcuts import render, redirect
from django.views import generic
from Contact_Info_Adminstration.models import Contact_MAKANI_CF,SearchQuery

from Contact_Info_Adminstration.forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse



from learning_user import settings

from django.contrib.auth.decorators import login_required



class PostList(generic.ListView):
    context_object_name= 'post_list'
    queryset = Contact_MAKANI_CF.objects.filter(status=1).order_by('-created_on')
    template_name = 'Contact/index.html'  # a list of all posts will be displayed on index.html
    model = Contact_MAKANI_CF



class PostDetail(generic.DetailView):
    model = Contact_MAKANI_CF
    template_name = 'Contact/post_detail.html'  # detail about each Contact  post will be on post_detail.html






@login_required
def contact_form(request):
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = f'Message Pour  Sujet De : {form.cleaned_data["Sujet"]}  , from email : {form.cleaned_data["email"]}'
            message = form.cleaned_data["Message_Detailles"]
            sender = form.cleaned_data['email']
            recipients = settings.EMAIL_HOST_USER
            try:
                send_mail(subject, message, [sender], [recipients], fail_silently=True)
            except BadHeaderError:
                return HttpResponse('Invalid header found')
            return HttpResponse('Success...Your email has been sent')
    return render(request, 'Contact/contact.html', {'form': form})



###########   2020-05-15 ##########"""
from Poste_By_Admin.models import BlogPost

def search_view(request):
    query = request.GET.get('q', None)
    user = None
    if request.user.is_authenticated:
        user = request.user
    context =  {"query": query}
    if query is not None:
        SearchQuery.objects.create(user=user, query=query)
        blog_list = BlogPost.objects.search(query=query)
        context['blog_list'] = blog_list
    return render(request, 'searches/view.html',context)

learning_user/Contact_Info_Adminstration/templates/Contact/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
  <meta charset="utf-8">
  <title>Makani</title>
  

   
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "css/font-awesome.min.css" %}">
  <link rel="stylesheet" href= "{% static "css/main.css" %}">




</head>
<body>




    <style>
        body{
            font-family: "Roboto", sans-serif;
            font-size: 17px;
            background-color: #fdfdfd;

        }



        .footer {
            position: fixed;
            left: 0;
            bottom: 0;
            width: 100%;
            background-color: #3398E1;
            color: white;
            text-align: center;
        }

        .shadow {
            box-shadow: 0 4px 2px -2px rgba(0, 0, 0, 0.1);
        }

        .btn-danger {
            color: #fff;
            background-color: #f00000;
            border-color: #dc281e;
        }

        .masthead{
            background: #3398E1;
            height: auto;
            padding-bottom: 15px;
            box-shadow: 0 16px 48px #E3E7EB;
            padding-top: 10px
        }




    </style>



  <!--start Upper Navbar-->
  <div class="upper-bar">
    <div class="container">
      <div class="row">
        <div class="col-sm">
          <i class="fa fa-phone"></i> <span>07100089000</span> ,
          <i class="fa fa-envelope"></i> MembreMakani@MAKANI.CF
        </div>
        <div class="col-sm text-right">
          <span>let's Share </span>
          2020 ... 
          <span class="get-Quoat"> Easy with Us </span>
        </div>

      </div>
    </div>

  </div>



  <nav class="navbar navbar-expand-lg navbar-light ">
    <div class=" container">
      <a class="navbar-brand" href="{% url 'Contact_Info_Adminstration:home' %}">
        <span>MAKANI</span><span>- CF -From Contact</span>
      </a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span> OPTIONS  </button>



      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
     

           <li class="nav-item">
              <a  class="nav-link" href="{% url 'homme' %}" > Homme </a>
             </li>


    
      
      
     
  {% if user.is_authenticated %}
      
        <li class="nav-item active ">
        <a  class="nav-link" href="{% url 'logout' %}"> Logout</a>
      </li>

          {% if user.is_evaluteur %}
        <li class="nav-item active ">
        <a  class="nav-link"  href="{% url "evaluteur:dashboardeval" %}"> Back to Profile </a>
         </li>

          {% endif %}  
      

         
           {% if user.is_chercheur %}
   <li class="nav-item active ">
        <a  class="nav-link"  href="{% url "chercheur:dashboardchrch" %}"> Back to Profile </a>
         </li>
          {% endif %}  

 
     {% else %}
 
           <li class="nav-item active ">
            <a class="nav-link" href="{% url 'login' %}">Login </a>
          </li>


         
         
<li>
    <a href="{% url 'chercheur_signup' %}">Chercheur account</a> 
    or a <a href="{% url 'evaluteur_signup' %}">Evaluteur account</a>.
</li>



  {% endif %}

<li class="nav-item">
              <a  class="nav-link" href="{% url 'Contact_Info_Adminstration:contact' %}" > Contact Now ! </a>
             </li>


       


        </ul>
      </div>
    </div>

  </nav>


    {% block content %}
     <!--Content Goes Here-->
    {% endblock content%}





<br><br>


<div class=" Copyright">
  <div class="container">
    <div class="row">
      <div class="col text-left text-uppercase">
        Copyright 2020 MAKANI_cf &copy All Right Riserved
      </div>
      <div class="col text-right">
        <ul class="list-unstyled">
          <li>
            <a href="#"> <i class="fa fa-facebook"></i></a>
          </li>
          <li>
            <a href="#"> <i class="fa fa-envelope"></i></a>
          </li>
          <li>
            <a href="#"> <i class="fa fa-instagram"></i></a>
          </li>
          <li>
            <a href="#"> <i class="fa fa-google-plus"></i></a>
          </li>

        </ul>

      </div>

    </div>
  </div>
</div>
    {% include 'Poste_by_Admin/js.html' %}
</body>
</html>

learning_user/Contact_Info_Adminstration/templates/Contact/contact.html
{% extends 'accounts/main.html'%}
{% block content %}

<style>
        .container{
             padding-top: 15px;
        }

    #id_name{
        width:100%
        }

    #id_message{
        width:100%
        }

    #id_email{
        width:100%
        }
</style>

<div class="content">
        <div class="row">
          <div class=" col-lg-12 col-md-12">
            <div class="card  ">
              <div class="card-header text-center">

              </div>
              <div class="card-body-center">
                <form method="post">
                    <div class="col-sm-6">
                     <h2>Send Message</h2>
                       <form action="" method="POST">
        {% csrf_token %}

        {% for hidden in form.hidden_fields %}
        {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
        <div class="form-group">
            {{ field.errors }}
            <label>{{ field.label_tag }}</label>
            <p>{{ field }}</p>
        </div>
        {% endfor %}
        <button type="reset" class="btn btn-secandery">Reset</button>
         <button type="submit" class="btn btn-primary">Send</button>
    </form>
</div>
                </form>
              </div>
            </div>
          </div>
        </div>
    </div>


<div class="fixed-plugin">
    <div class="dropdown show-dropdown">
      <a href="#" data-toggle="dropdown">
        <i class="fa f <div a-cog fa-2x"> </i>
      </a>
      <ul class="dropdown-menu">
        <li class="header-title"> Sidebar Background</li>
        <li class="adjustments-line">
          <a href="javascript:void(0)" class="switch-trigger background-color">
            <div class="badge-colors text-center">
              <span class="badge filter badge-info " data-color="primary"></span>
              <span class="badge filter badge-primary active" data-color="blue"></span>
              <span class="badge filter badge-success" data-color="green"></span>
            </div>
            <div class="clearfix"></div>
          </a>
        </li>
        <li class="adjustments-line text-center color-change">
          <span class="color-label">LIGHT MODE</span>
          <span class="badge light-badge mr-2"></span>
          <span class="badge dark-badge ml-2"></span>
          <span class="color-label">DARK MODE</span>
        </li>


      </ul>
    </div>
  </div>

{% endblock content %}

learning_user/Contact_Info_Adminstration/templates/Contact/index.html
{% extends 'Contact/base.html' %}
{% block content %}

<style>
    body {
        font-family: "Roboto", sans-serif;
        font-size: 18px;
        background-color: #fdfdfd;
    }

    .head_text{
        color: white;
    }

    .card{
        box-shadow: 0 16px 48px #E3E7EB;
    }

</style>

<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class=" col-md- col-md-10 mx-auto">
                <div class="site-heading">

                    <h3 class=" site-heading my-4 mt-3 text-white">
                     {% if user.is_authenticated %}
                        Welcome to  Contact  CF-Makani-_Admin  :  {{ user.username }}
                        {% else %}
                        Welcome to  Contact CF-Makani-_Admin
                        {% endif %}
                    </h3>
                    <p class="text-light"> Awsome !!! &nbsp;
                    </p>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        <!-- Blog Entries Column -->
        <div class="col-md-8 mt-3 left">
     
            {% for post in post_list %}
            
            <div class="card mb-4">
                <div class="card-body">
                    <h2 class="card-title">
              | Pour le Contact Generale  de :
                    {{post.title_de_problem }}</h2>
                    <p class="card-text text-muted h6">
                    | merci et  conatcte nous , by :{{ post.Perssone }} </p>
                    <p class="card-text text-muted h6">
            | Date de reglage cette Contact  :{{ post.created_on}}</p>
                    <p class="card-text">{{post.content|slice:":200" }}</p>
                    <a href="{% url 'Contact_Info_Adminstration:post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                </div>
            </div>
            {% endfor %}
        </div>
      
    </div>
</div>
{%endblock%}

learning_user/Contact_Info_Adminstration/templates/Contact/post_detail.html
{% extends 'Contact/base.html' %}
{% block content %}

<div class="container">
    <div class="row">
        <div class="col-md-8 card mb-4 mt-3 left top">
            <div class="card-body">
                <h2> Titre de cette Contact :</h2>
                <h1>{% block title %}
                 {{ object.title_de_problem }} 
               {% endblock title %}</h1>
               <h4>Merci pour contact redige par Nous : </h4>
                <p class="text-muted"> {{ object.Perssone }} | {{ object.created_on }} </p>
                <h3> Rusultat de cette Contact : </h3>
                <p class="card-text"> {{ object.content }}</p>
            </div>
        </div>

    </div>
</div>

{% endblock content %}