learning_user/accounts/urls.py
from django.urls import path
from . import views
from .views import (evalList, EvalCreateView, EvalUpdateView, EvalDeleteView,
    cherList, CherCreateView, CherDeleteView, CherUpdateView, HomePageView

,confList,ConfUpdateView,ConfCreateView,
ConfDeleteView,ConfDetailView,ArticlList_Conf, Confmodifier

,ComiteCreateView, ComiteUpdateView
    )



urlpatterns = [
    
    # les liste li3ndnaaaaaaaaaaaaaaaaaaaa ga3 f jiha t3na admin 
    path('',HomePageView.as_view(),name ="dashboard"),
    path('gest_eval/', evalList.as_view(), name="ges_eval"),
    path('gest_cher', cherList.as_view(), name="ges_cher"),
     path('gest_conf/', confList.as_view(), name="ges_conf"),




#++++++++++++++++++++++ admin men jihete chandiire lel  eval
    path('evalEdit/<str:pk>/', EvalUpdateView.as_view(), name="editEval"),
    path('evalCreate/', EvalCreateView.as_view(), name="createEval"),
    path('<pk>/deleteEval/', EvalDeleteView.as_view(), name="deleteEval"), 
  

#++++++++++++++++++++++++++ admin men jihete chandiire lel  chrchr
    
    path('editCher/<str:pk>/', CherUpdateView.as_view(), name="editCher"),
    path('createCher/', CherCreateView.as_view(), name="createCher"),
    path('<pk>/deleteCher/', CherDeleteView.as_view(), name="deleteCher"),
   

         

    # hadi kante aapliaction smoha Gconf ms ni hatiteh f account bch ndiro 
    #app wahde lel adminnstration  w kate dyera des prblm  ni riglthoom rahi f chbebe
    
    #++++++++++++++++++++++++++ admin men jihete chandiire lel  cConfrencess

   
    path('confEdit/<str:pk>/', ConfUpdateView.as_view(), name="confEdit"),
    path('confCreate/', ConfCreateView.as_view(), name="confCreate"),
    path('<pk>/deleteConf/', ConfDeleteView.as_view(), name="deleteConf"), 
    path('confDetail/<str:pk>/', ConfDetailView.as_view(), name="confDetail"),
    path('modifier/<str:pk>/', Confmodifier.as_view(), name="modifier"),
    
    
    
# +++++++ 2020/05/15 +++++++++
    path('article_conf/<str:pk>/',ArticlList_Conf,name='article_conf'),
    path('comiteCreate',ComiteCreateView.as_view(),name='comiteCreate'),
    path('comiteEdit/<str:pk>/', ComiteUpdateView.as_view(), name="comiteEdit"),
    
  



    
]


    

learning_user/learning_user/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views as viewsPj
from mybasic_app.views import chercheur, evaluteur,views
from django.conf import settings



#####################
from Contact_Info_Adminstration.views import search_view




urlpatterns = [
    path('1salah2toufik3ahmed4islam5nadjet6nariman789/', admin.site.urls), #hadaa path tree essencieles attention
    path('',viewsPj.Homme,name='homme'),
    path('AbouteUs',viewsPj.Aboute__Us,name='Aboute__Us'),



    path('myapp/',include('mybasic_app.urls')),
    path('logout/',views.user_logout,name="logout"),
     path('contact/', include('Contact_Info_Adminstration.urls')),



######
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/chercheur/', chercheur.ChercheurSignUpView.as_view() , name='chercheur_signup'),
    path('accounts/signup/evaluteur/', evaluteur.EvaluteurSignUpView.as_view(), name='evaluteur_signup'),

################## note perssonel
    path('<int:id>',views.mylist, name="mylist"),


#++++++++++++++++++++++++++++++++++++++++++++++++++++#partie adminstration 
path('MakaniAdmin/', include('accounts.urls'),name='MakaniAdmin'),

#############  2020/05/15   ########"
    path('Info-Poste', viewsPj.Poste_page,name='Info_Poste'),
    path('blog/', include('Poste_By_Admin.urls')),
    path('search/', search_view,name='searching'),




############      2020 / 05 / 18 ################""""

    path('G__evaluation/', include('G__evaluation.urls')),






]


if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_user/mybasic_app/urls.py
from django.urls import path,include
from .views import chercheur,evaluteur,views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    
     path('login/',views.LoginByProfile, name="LoginByProfile"),

    


###################""


  path('myapp/chercheur/', include(([
  	  path('', chercheur.profil_chrch, name='dashboardchrch'),
      path('contact',chercheur.ToContact , name='Contact_chrch_ou_admin'),
      path('myprofile_AsChercheur',chercheur.Userchrch,name='Profile'),
      path('CréaArticle',chercheur.CreeArticle,name='CreeArticle'),
      path('DeleteARTCL',chercheur.Delete_list,name='list_delete_Article'),
      path('UpdateARTCL',chercheur.Update_detaille_list,name='tach_ARTCL'),
      path('Documentation_chrh/',chercheur.AccedeauDoc_Aschrch,name='AccedeauDoc_Aschrch'),
      path('EditeProfile/<str:pk>/',chercheur.Edit_Myprofil.as_view(),name='EditeProfile'),
              # ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++   10/05/2020     ++++++++++++++++++++++++++++++++++
  
      path('DeleteARTCL/<str:pk>/',chercheur.Delete,name='Delate'),
      path('UpdateArTCL/<str:pk>/',chercheur.Update,name='Update'),
              # +++++++++++++++++++++++++++++++++++++++++++++   15/05/2020     ++++++++++++++++++++++++++++++++++
      path('conf_list/<str:pk>/',chercheur.confList,name='conf_list'),
      path('conf_detaille/<str:pk>/',chercheur.ConfDetailView.as_view(),name='conf_detaille'),
      path('topic_list/',chercheur.topicList.as_view(),name='topic_list'),



    

                                     ], 'views'), namespace='chercheur')),





    path('myapp/evaluteur/', include(([

       path('', evaluteur.profil_eval , name='dashboardeval'), # hadi engenrale
       path('contact',evaluteur.ToContact , name='Contact_eval_ou_admin'),
       path('myprofileAsEvaluateur/',evaluteur.Usereval,name='Profile'),  # hadi sepecile lel user
       path('Articles/',evaluteur.Liste_All_Artcl.as_view(), name='listeArtcile'),
       path('Confrences/',evaluteur.Liste_All_Confrence.as_view() , name='All_Confernce'),
       path('Liste/',evaluteur.all_list , name='listeNv'),# z3ma ga3 les them wla confrence
       path('Evalution/',evaluteur.evaluéé , name='evaluéé'),
       path('Documentation_evl',evaluteur.AccedeauDoc,name='AccedeauDoc'),
       path('EditeProfile/<str:pk>/',evaluteur.Edit_Myprofil_As_Eval.as_view(),name='EditeProfileAs_eval'),
       path('etat_chrch/',evaluteur.All_Etat_Du_Cherchr.as_view() , name='Etat_All_Chrch'),


       path('Allcommite/',evaluteur.All_Commite.as_view() , name='AllCommite'),
       #path('Votrecommite/',evaluteur.Mon_Commite.as_view() , name='MonCommite'),





                                      ], 'views'), namespace='evaluteur')),





###############" hado swalhe persssonel t3 kol user bch ytfkre wla ki agendaa "

    path('create/',views.createNote, name="create"),
    path('mynote/',views.mynote, name="mynote"),
    path('merci/',views.Merci, name="merci"),


  


    
        ]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning_user/mybasic_app/views/chercheur.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView,DetailView
from ..decorators import chercheur_required
from ..forms import ChercheurSignUpForm,From_Edite_Profile,ArticleForm,ConfForm
from ..models import User,Chercheur ,Article,Topic,Conferance

# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
from django.forms import inlineformset_factory
from django.core.files.storage import FileSystemStorage




#+++++++++++++++++
from mybasic_app.filters import FilterClass





class ChercheurSignUpView(CreateView):
	model = User
	form_class = ChercheurSignUpForm
	template_name = 'registration/signup.html'

	def get_context_data(self, **kwargs):
		kwargs['user_type'] = 'chercheur'

		return super().get_context_data(**kwargs)


	def form_valid(self ,form):
		user = form.save()
		login(self.request, user)
		return redirect('chercheur:dashboardchrch') 





@login_required
@chercheur_required
def profil_chrch(request):
	return render(request, 'Templchercheur/profil_chrch.html')


@login_required
@chercheur_required
def ToContact(request):
	return render(request, 'Templchercheur/contactAS_chrcheur.html')



@login_required
@chercheur_required
def Userchrch(request):

	return render(request, 'Templchercheur/profile-page.html')


'''

@login_required
@chercheur_required
def AccedeauDoc_Aschrch(request):
	return render(request, 'Templchercheur/docs/documentation.html')
'''


#+++++++++++++++++++++++++++++++++++++++++++++     10/06/2020   +++++++++++++++++++++++++++++-

@login_required
@chercheur_required
def CreeArticle(request ):

	User = request.user
	formset = ArticleForm()   
	if request.method == 'POST':
		formset = ArticleForm(request.POST , request.FILES)
			   
		if formset.is_valid():
			 article = formset.save(commit=False)
			 article.date_posté
			 article.author = Chercheur.objects.get(user=User)
			 article.save()
			 return redirect('chercheur:tach_ARTCL')

	context = {'formset': formset }
	return render(request, 'Templchercheur/register-page.html' ,context)






@login_required
@chercheur_required
def Delete_list(request):
	User = request.user
	researcher = Chercheur.objects.get(user=User)
	articles = Article.objects.filter(author = researcher)
	myfilter=FilterClass(request.GET , queryset=articles)
	articles = myfilter.qs
	context = {'articles': articles ,'myfilter':myfilter}
	return render(request, 'Templchercheur/Delete_List_Article.html' , context)






@login_required
@chercheur_required
def Delete(request , pk):
	User = request.user
	researcher = Chercheur.objects.get(user=User)
	article = Article.objects.filter(author = researcher).get(pk = pk)
	article.delete()
	return redirect('chercheur:list_delete_Article')




@login_required
@chercheur_required
def Update_detaille_list(request):
	User = request.user 
	researcher = Chercheur.objects.get(user=User)
	articles = Article.objects.filter(author = researcher) ##++++++++++++++ chkon li dar hada aartcile
   ############              #######      ##########
	#chrch = chercheur.objects.all()
	myfilter=FilterClass(request.GET , queryset=articles)
	articles = myfilter.qs
	context = {'articles': articles ,'myfilter':myfilter}
	
	return render(request, 'Templchercheur/les_articl_Detailles.html' , context)




@login_required
@chercheur_required
def Update(request ,pk ):

	User = request.user
	researcher = Chercheur.objects.get(user=User) ##+++++++++++++++  chkon li dar hada aartcile
	article = Article.objects.filter(author = User.id ).get(pk = pk)
	formset = ArticleForm(instance = article)
	
	if request.method == 'POST':
		formset = ArticleForm(request.POST , request.FILES  ,instance = article)
   
		if formset.is_valid():
			 article = formset.save(commit=False)
			 article.date_posté
			 article.author = Chercheur.objects.get(user=User)
			 article.Conferance.name = formset.cleaned_data['Conferance']
			 article.save()
			 return redirect('chercheur:tach_ARTCL')

	context = {'formset': formset}
	return render(request, 'Templchercheur/modifèè.html' ,context)






####################
@method_decorator([login_required, chercheur_required], name='dispatch')
class Edit_Myprofil(UpdateView):
	template_name = 'Templchercheur/edite_myprofil.html'
	model = User
	form_class = From_Edite_Profile

	def get_success_url(self):
		return reverse_lazy('chercheur:Profile')
	 


'''
hadi khaliha aprr nsthe9aha f filter apree  !!!! 

	def get_queryset(self):
		qs = self.model.objects.all()
		list_td = FilterClass_prfl(self.request.GET, queryset=qs)
		return list_td.qs
'''


@login_required
@chercheur_required
def AccedeauDoc_Aschrch(request):
	User = request.user
	chrch = Chercheur.objects.get(user=User) 
	articles = Article.objects.filter(author = chrch )
	context = {'articles': articles}
	return render(request, 'Templchercheur/docs/documentation.html',context)



# +++++++++++++++++++++++++++++++++++ 2020/05/15   +++++++++++++++++++++++++++++
  
@login_required
@chercheur_required
def confList(request, pk):
    topic = Topic.objects.get(id = pk)
    conferances= Conferance.objects.filter(topic = topic)
    conf_count = conferances.count()
    context = {'topic':topic, 'conferances':conferances, 'conf_count':conf_count}

    return render(request, 'Templchercheur/All_Confernce.html', context)





@method_decorator([login_required, chercheur_required], name='dispatch')
class topicList(ListView):
   template_name = 'Templchercheur/All_Topics.html'
   model = Topic        
   paginate_by = 5

   def get_context_data(self, **kwargs):
    context = super().get_context_data(**kwargs)
    context['number'] = Topic.objects.all().count()
    return context   




@method_decorator([login_required, chercheur_required], name='dispatch')
class ConfDetailView(DetailView):
    template_name = 'Templchercheur/Conf_Detailles.html'
    model = Conferance
    form_class = ConfForm

learning_user/mybasic_app/views/evaluteur.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import (CreateView, DeleteView, DetailView, ListView,
                                  UpdateView)

from ..decorators import evaluteur_required
from ..forms import  EvaluteurSignUpForm,From_Edite_Profile
from ..models import  User,Evaluateur,Article,Conferance,Commite

from django.http import HttpResponseRedirect, HttpResponse




class EvaluteurSignUpView(CreateView):
    model = User
    form_class = EvaluteurSignUpForm
    template_name = 'registration/signup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'evaluteur'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        #if Evaluteur.Code_Eval =="makani" :
        user = form.save()
        login(self.request, user)
        return redirect('evaluteur:dashboardeval')         # hadi dashboard en genralle ga33
        #else :
            #return HttpResponseRedirect(reverse('homme'))






@login_required
@evaluteur_required
def profil_eval(request):
	return render(request,'Templevaluteur/Dachboardeval.html')




@login_required
@evaluteur_required
def ToContact(request):
    return render(request,'Templevaluteur/contactAs_evaluteur.html')




@login_required
@evaluteur_required
def Usereval(request):
    return render(request,'Templevaluteur/ProfileEval.html')






@login_required
@evaluteur_required
def all_list(request):
    return render(request,'Templevaluteur/List_Artcl_Evaluee.html')


@login_required
@evaluteur_required
def evaluéé(request):
    return render(request,'Templevaluteur/evaluation.html')


@login_required
@evaluteur_required
def AccedeauDoc(request):
    return render(request,'Templevaluteur/docs/documentation.html')




####################
@method_decorator([login_required, evaluteur_required], name='dispatch')
class Edit_Myprofil_As_Eval(UpdateView):
    template_name = 'Templevaluteur/Eval_edite_myprofile.html'
    model = User
    form_class = From_Edite_Profile
    
    def get_success_url(self):
        return reverse_lazy('evaluteur:Profile')
     



#+++++++++++++++++++++++++++++++++++++
@method_decorator([login_required, evaluteur_required], name='dispatch')
class Liste_All_Artcl(ListView):
    model = Article
    template_name = 'Templevaluteur/All_Artcles.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nbrArctl'] = Article.objects.all().count()
        return context




@method_decorator([login_required, evaluteur_required], name='dispatch')
class Liste_All_Confrence(ListView):
    model = Conferance
    template_name = 'Templevaluteur/All_Conf.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nbrConf'] = Conferance.objects.all().count()
        return context        



@method_decorator([login_required, evaluteur_required], name='dispatch')
class All_Etat_Du_Cherchr(ListView):
    model = User
    template_name = 'Templevaluteur/All_chercheur.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nbrchrch'] = User.objects.filter(is_chercheur=True).count()
        return context        




@method_decorator([login_required, evaluteur_required], name='dispatch')
class All_Commite(ListView):
    model = Commite
    template_name = 'Templevaluteur/All_Commite.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['nbrCommite'] = Commite.objects.all().count()
        return context        

learning_user/mybasic_app/templates/Templchercheur/Delete_List_Article.html
{% extends 'Templchercheur/mainchr.html' %}
{% load static %}
{% block body_block %}
 

  <div class="wrapper">
    <div class="page">
      <img src="{% static 'G-Admin_cherch_eval/img/dots.png' %}" class="dots">
      <img src="{% static 'G-Admin_cherch_eval/img/path1.png' %}" class="path">

<div class="content">
        <div class="row">
          <div class="col-md-8 ml-auto mr-auto">
            <div class="card card-upgrade text-center">
              <div class="card-header text-center">
                <h4 class="card-title">list of Articles </h4>
                  <p class="card-category">
<h1> User :{{ user.username }} ,</h1>
<h2>  Il existe {{articles.count }} Article </h2>
  <br><br><br><br>
 

{% if articles|length > 0 %}

  <h2 style="color:#ffffff;"> Attention ! </h2>
   <p>
this deletion definitely! Final confirmation otherwise Article Clicker you can delete! !</p>




        {% for art in articles %}

        <div class="btn-wrapper pt-3">
          <a href="{% url 'chercheur:Delate' art.id %}">
            <button href="{% url 'chercheur:Delate' art.id %}" class="btn btn-simple btn-primary">
              <i class="tim-icons icon-paper"></i>
               {{art}}
            </button>
          </a>
        </div>

        {% endfor %}
{% else %}
  <h3 style="color:blue;">
* There are no articles To delete!  </h3>
    <h5>
Create a new <a href="{% url 'chercheur:CreeArticle' %}">Create</a></h5>
 {% endif %}
        
      </div>
    </div>
  </div>

</div>
            </div>
          </div>
        </div>
</div>
{% endblock %}

learning_user/mybasic_app/templates/Templchercheur/contactAS_chrcheur.html
{% extends 'account/mybase.html' %}

{% block body_block %}




{% endblock %}

learning_user/mybasic_app/templates/Templchercheur/mainchr.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="apple-touch-icon" sizes="76x76" href="{% static 'G-Admin_cherch_eval/img/apple-icon.png' %}">

  <title>
Profile
  </title>
  <!--     Fonts and icons     -->
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,400,600,700,800" rel="stylesheet" />
  <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
  <!-- Nucleo Icons -->
  <link href="{% static 'G-Admin_cherch_eval/css/nucleo-icons.css' %}" rel="stylesheet" />
  <!-- CSS Files -->
  <link href="{% static 'G-Admin_cherch_eval/css/blk-design-system.css' %}" rel="stylesheet" />
  <!-- CSS Just for demo purpose, don't include it in your project -->
  <link href="{% static 'G-Admin_cherch_eval/demo/demo.css' %}" rel="stylesheet" />
</head>


<body class="profile-page">
   <!-- Navbar -->
  <nav class="navbar navbar-expand-lg fixed-top navbar-transparent " color-on-scroll="100">
    <div class="container">
      <div class="navbar-translate">
        <a class="navbar-brand" href="{% url 'homme' %}" rel="tooltip" title="" data-placement="bottom" target="_blank">
          <span>MAKANI-</span> cf
        </a>



        <button class="navbar-toggler navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-bar bar1"></span>
          <span class="navbar-toggler-bar bar2"></span>
          <span class="navbar-toggler-bar bar3"></span>
        </button>
      </div>
<div class="container">
      <div class="collapse navbar-collapse justify-content-end" id="navigation">
        <div class="navbar-collapse-header">
          <div class="row">
            <div class="col-6 collapse-brand">
              <a>
                
              </a>
            </div>
            <div class="col-6 collapse-close text-right">
              <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navigation" aria-controls="navigation-index" aria-expanded="false" aria-label="Toggle navigation">
                <i class="tim-icons icon-simple-remove"></i>
              </button>
            </div>
          </div>
        </div>
        <ul class="navbar-nav">

          <li class="nav-item p-0">
            <a class="nav-link" rel="tooltip" title="Follow us on Twitter" data-placement="bottom" href="#" target="_blank">
              <i class="fab fa-twitter"></i>
              <p class="d-lg-none d-xl-none">Twitter</p>
            </a>
          </li>
          <li class="nav-item p-0">
            <a class="nav-link" rel="tooltip" title="Like us on Facebook" data-placement="bottom" href="#" target="_blank">
              <i class="fab fa-facebook-square"></i>
              <p class="d-lg-none d-xl-none">Facebook</p>
            </a>
          </li>
          <li class="nav-item p-0">
            <a class="nav-link" rel="tooltip" title="Follow us on Instagram" data-placement="bottom" href="#" target="_blank">
              <i class="fab fa-instagram"></i>
              <p class="d-lg-none d-xl-none">Instagram</p>
            </a>
          </li>









          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              <i class="fa fa-cogs d-lg-none d-xl-none"></i> My Profile
            </a>
            <div class="dropdown-menu dropdown-with-icons">
            
                 <a href="{% url 'chercheur:Profile' %}" class="dropdown-item">
                <i class="tim-icons icon-single-02"></i>Profile P
                     age
              </a>


                 
            <a href="{% url 'mynote' %}" class="dropdown-item">
                <i class="tim-icons icon-single-02"></i> See My note 
            </a>
          


  
            <a href="{% url 'create' %}" class="dropdown-item"  >  
             <i class="tim-icons icon-single-02"></i>create Note 
            </a>
          

           
            <a href="{% url 'Create_Newblog' %}" class="dropdown-item" >
              <i class="tim-icons  icon-single-02">
                         </i>   create blog Now 
           
            </a>



          

            <a href="{% url 'My_List_Blog' %}" class="dropdown-item" >
              <i class="tim-icons  icon-single-02">
                         </i>   voir my blog 
           
            </a>

                 <a href="{% url 'chercheur:Contact_chrch_ou_admin' %}" class="dropdown-item">
                <i class="tim-icons icon-single-02"></i> Contact Us
              </a>
                       

                 <a href="{% url 'chercheur:AccedeauDoc_Aschrch' %}" class="dropdown-item">
                <i class="tim-icons icon-single-02"></i> Documentation
                  </a>    


              


                 </div>

          </li>
          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              <i class="fa fa-cogs d-lg-none d-xl-none"></i> Getting started
            </a>

            <div class="dropdown-menu dropdown-with-icons">

      

              <a href="{% url 'chercheur:tach_ARTCL' %}" class="dropdown-item">
                <i class="tim-icons icon-paper"></i> 
                 My Articles
              </a>
              <a href="{% url 'chercheur:CreeArticle' %}" class="dropdown-item">
                <i class="tim-icons icon-bullet-list-67"></i>Add article
              </a>
              <a href="{% url 'chercheur:list_delete_Article' %}" class="dropdown-item">
                <i class="tim-icons icon-simple-remove"></i>Delete article 
              </a>


              </div>
       </li>

          <li class="dropdown nav-item">
            <a href="#" class="dropdown-toggle nav-link" data-toggle="dropdown">
              <i class="fa fa-cogs d-lg-none d-xl-none"></i> Gestion important
            </a>

                      <div class="dropdown-menu dropdown-with-icons">
               <a href="{% url 'chercheur:topic_list' %}" class="dropdown-item">
                <i class="tim-icons icon-single-02"></i> Some Informations
              </a>
              
             <a href="#" class="dropdown-item">
                <i class="tim-icons icon-single-02">
                  
                </i>  Notification
              </a>
              </div> 
            
</li>
</ul>
<br><br><br>
</div>

</div>

</nav>



  <!-- End Navbar -->
   <br><br><br><br>
 
{% block body_block %}



{% endblock %}

   <br><br><br><br>





  </div>
  <!--   Core JS Files   -->
  <script src="{% static 'G-Admin_cherch_eval/js/core/jquery.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'G-Admin_cherch_eval/js/core/popper.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'G-Admin_cherch_eval/js/core/bootstrap.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'G-Admin_cherch_eval/js/plugins/perfect-scrollbar.jquery.min.js' %}"></script>
  <!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
  <script src="{% static 'G-Admin_cherch_eval/js/plugins/bootstrap-switch.js' %}"></script>
  <!--  Plugin for the Sliders, full documentation here: http://refreshless.com/nouislider/ -->
  <script src="{% static 'G-Admin_cherch_eval/js/plugins/nouislider.min.js' %}" type="text/javascript"></script>
  <!-- Chart JS -->
  <script src="{% static 'G-Admin_cherch_eval/js/plugins/chartjs.min.js' %}"></script>
  <!--  Plugin for the DatePicker, full documentation here: https://github.com/uxsolutions/bootstrap-datepicker -->
  <script src="{% static 'G-Admin_cherch_eval/js/plugins/moment.min.js' %}"></script>
  <script src="{% static 'G-Admin_cherch_eval/js/plugins/bootstrap-datetimepicker.js' %}" type="text/javascript"></script>
  <!-- Black Dashboard DEMO methods, don't include it in your project! -->
  <script src="{% static 'G-Admin_cherch_eval/demo/demo.js' %}"></script>
  <!-- Control Center for Black UI Kit: parallax effects, scripts for the example pages etc -->
  <script src="{% static 'G-Admin_cherch_eval/js/blk-design-system.min.js' %}" type="text/javascript"></script>
  


  <script>
    $(document).ready(function() {
      blackKit.initDatePicker();
      blackKit.initSliders();
    });

    function scrollToDownload() {

      if ($('.section-download').length != 0) {
        $("html, body").animate({
          scrollTop: $('.section-download').offset().top
        }, 1000);
      }
    }
  </script>
</body>



</html>